### ISSUE TITLE
causing server crashes on 1.19.4

### ISSUE THREAD

**Issue by Devilswarchild** [Cristelknight999/Cristel-Lib#1]
trying to start a server in order to make a working server pack for my modpack MineColonies: Dimensional Adventure and got a crash report labeling this mod as the culprit for the error.

crash report is attached,

[crash-2023-06-12_13.16.28-fml.txt](https://github.com/Cristelknight999/Cristel-Lib/files/11726890/crash-2023-06-12_13.16.28-fml.txt)
[debug.log](https://github.com/Cristelknight999/Cristel-Lib/files/11726949/debug.log)
[latest.log](https://github.com/Cristelknight999/Cristel-Lib/files/11726968/latest.log)

**Comment by Cristelknight999** [comment]
It is fixed in the latest forge version. (Re-uploaded as the same version)
