### ISSUE TITLE
[1.20.1] Crash When Loading or Creating World

### ISSUE THREAD

**Issue by SaltSouls** [Cristelknight999/Cristel-Lib#10]
## Description:
Whenever I try and boot up or create a world my game crashes. The game seems to think it is an incompatibility between Cristel-Lib and FPS Reducer. Though when looking through the logs, the crash seems to be related to the way this mod handles its built-in data/resource packs.

## Versions:
- Forge: 47.2.4
- Cristel-Lib: 1.1.5
- FPS Reducer: 1.20-2.5

## Logs:
[latest.log](https://github.com/Cristelknight999/Cristel-Lib/files/13289869/latest.log) |  [debug.log](https://github.com/Cristelknight999/Cristel-Lib/files/13289870/debug.log)

**Comment by SaltSouls** [comment]
A little update. It has nothing to do with FPS Reducer. The game just crashes any time a new world is attempted to be created or an old world is loaded.

**Comment by PlayfulPiano** [comment]
can also confirm getting the same crash after updating cristel lib
[crash-2023-11-07_19.40.29-client.txt](https://github.com/Cristelknight999/Cristel-Lib/files/13290680/crash-2023-11-07_19.40.29-client.txt)

**Comment by ModifiedMC** [comment]
[crash-2023-11-07_21.38.30-client.txt](https://github.com/Cristelknight999/Cristel-Lib/files/13291413/crash-2023-11-07_21.38.30-client.txt)
Same here

**Comment by hazerddex** [comment]
also crashing after new update.
[crash-2023-09-27_13.19.23-client.txt](https://github.com/Cristelknight999/Cristel-Lib/files/13292123/crash-2023-09-27_13.19.23-client.txt)

everything else was working fine before the update as well. I added no new mods from the last time I played.

**Comment by KochamDara** [comment]
[crash-2023-11-08_17.08.16-client.txt](https://github.com/Cristelknight999/Cristel-Lib/files/13298986/crash-2023-11-08_17.08.16-client.txt)
Can confirm the newest version makes me crash when trying to load the world. Custom modpack with around 260 mods on 1.20.1.
