### ISSUE TITLE
Crash on game startup with newest Cristel Lib version (1.1.5)

### ISSUE THREAD

**Issue by Zelioth** [Cristelknight999/Cristel-Lib#11]
Minecraft 1.20.1
Forge 47.2.1
CL : 1.1.5

Updating to the latest version of Cristel Lib seems to cause a crash on start up 

https://gist.github.com/Zelioth/244ee9918beb8af5b2335e808e43270d

**Comment by Mattsingen** [comment]
I also got a crash with 1.1.5, but on world load. The reason stated was the same.
Minecraft 1.20.1
Forge 47.2.4

Changing back to CL 1.1.3 solved the imidate issue, but isn't solving the root cause.

**Comment by Zedrimar** [comment]
A bit random, but that version of cristel lib is also incompatible with neoforge. Is there any way to change it? No changelog was uploaded with the new file, so I can't even tell if getting the new version is worth the update.
