### ISSUE TITLE
incomapibility with terrablender

### ISSUE THREAD

**Issue by nickademas** [Cristelknight999/Cristel-Lib#14]
[crash-2024-01-20_01.49.43-client.txt](https://github.com/Cristelknight999/Cristel-Lib/files/13996070/crash-2024-01-20_01.49.43-client.txt)
worked on terrablender 3.3.0.5 but crashes after launch in every later terrablender version

**Comment by bentterp** [comment]
+1 on this, crashes with only fabric, cristellib and terrablender enabled
https://mclo.gs/WWyqpvK

**Comment by Cristelknight999** [comment]
should be fixed in the newest version
