### ISSUE TITLE
Config 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [Cristelknight999/Cristel-Lib#19]
cristellib-1.1.5-forge.jar
[29Feb2024 19:30:03.134] [Render thread/ERROR] [Cristel Lib/]: Cristel Lib Config Pack has no data

**Comment by Norepinephrinee** [comment]
Same issue, MC 1.20.1, forge 47.3.5, towns and towers and cristel lib

[main/ERROR] [Cristel Lib/]: Cristel Lib Config Pack has no data
[main/ERROR] [Cristel Lib/]: T&T Waystone Patch Pack condition is false, skipping

**Comment by AqueleHaru** [comment]
same here. :$ any fix for that?

**Comment by Loowop** [comment]
Tengo el mismo problema, sobre todo levantando un servidor en el que planeo incluir towns and towers y me sale dicho error, no crashea, pero si aparece dicho error, no sé en qué ocasión podría generar el problema.

**Comment by massacring** [comment]
I'm having the same issue.
Is this harmless? Will there be a fix?

**Comment by Loowop** [comment]
> I'm having the same issue. Is this harmless? Will there be a fix?

Yo lo único que hice es reducir una versión de forge en la 1.20.1 y funcionó.

**Comment by M4rckR** [comment]
> > I'm having the same issue. Is this harmless? Will there be a fix?
> 
> Yo lo único que hice es reducir una versión de forge en la 1.20.1 y funcionó.

A que version la reduciste? Es que tengo miedo de que otros mods se veans perjudicados si lo hago

**Comment by Loowop** [comment]
> > > I'm having the same issue. Is this harmless? Will there be a fix?
> > 
> > 
> > Yo lo único que hice es reducir una versión de forge en la 1.20.1 y funcionó.
> 
> A que version la reduciste? Es que tengo miedo de que otros mods se veans perjudicados si lo hago

Versión 47.2.20, pero esto lo hice para un servidor, desde single player si juego desde 47.3.0

**Comment by Cristelknight** [comment]
fixed
