### ISSUE TITLE
Question: Is there a way to prevent random structure rotation with this mod?

### ISSUE THREAD

**Issue by Quatryl23** [Cristelknight999/Cristel-Lib#20]
For my structure datapack, which contains blocks from create mod, I need to prevent rotation because some blocks lose there data when rotated. Is there a way to fix that with the config from this mod?

**Comment by Cristelknight999** [comment]
No. This mod is only for creating configs for users to enable doable structures and change the frequency of structure spawns

**Comment by Quatryl23** [comment]
Thanks for the answer
