### ISSUE TITLE
Minecraft crashes when clicking on a single player.

### ISSUE THREAD

**Issue by kkawp** [Cristelknight999/Cristel-Lib#22]
The crash report indicates that the error is caused by a NullPointerException in the getPacks method of the BuiltInDataPacks class from the cristellib library. The exception occurs because the pack object is null. Here is the relevant part of the report:

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3262.method_14406(net.minecraft.class_3264)" because "pack" is null
    at net.cristellib.builtinpacks.BuiltInDataPacks.getPacks(BuiltInDataPacks.java:41)
    at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.handler$zje000$cristellib$loadPacks(ModResourcePackCreator.java:525)
    ...

**Comment by kkawp** [comment]
testing in win10 pro version 22h2 
API fabric 
game version: 1.20.6
mod version: 1.2.5

**Comment by Shadowpudding** [comment]
Same issue with mod version 1,2.6 for 1.21

**Comment by cobaltlol2** [comment]
> Same issue with mod version 1,2.6 for 1.21 when opening the world creation screen. It also prevents loading already made worlds.

Same problem for me

**Comment by Cristelknight999** [comment]
This should be fixed in Towns and Towers 1.13.2
