### ISSUE TITLE
Normal Structures not generating

### ISSUE THREAD

**Issue by jairusrs** [Cristelknight999/Cristel-Lib#24]
Hi I just installed Towns and towers mod, and it requires this Cristel-Lib, I found an issue where structures like strongholds do not spawn, this is quiet problematic for my server.

**Comment by Cristelknight** [comment]
Cristel lib doesn't change strongholds in any way. But I'll take a look at it in a few days

**Comment by Cristelknight** [comment]
did some testing and at least with the latest version i just can't reproduce this. i also can't imagine why this would happen trough this mod
