### ISSUE TITLE
1.20.1 cristellib crashes on quilt

### ISSUE THREAD

**Issue by temyy** [Cristelknight999/Cristel-Lib#3]
https://gist.github.com/temyy/4f5b1e92143f52ca83691c98b78b9bf2

cristellib 1.1.1, quilt loader 0.19.2. tried downgrading to 1.1.0 and it resulted in same error, 1.1.2 had a whole different error

**Comment by temyy** [comment]
nvm i deleted some configs and it just started working. i love minecraft modding

**Comment by bghyt** [comment]
What configs did you delete? I'm having the same issue.

**Comment by temyy** [comment]
honestly i forgot, i just cleared the whole config folder
