### ISSUE TITLE
Don't rely on AWT package

### ISSUE THREAD

**Issue by JaisDK** [Cristelknight999/Cristel-Lib#4]
Hi,

You can't rely on the AWT package to be available on all java installations, it's missing on a lot of linux dists.

https://github.com/Cristelknight999/Cristel-Lib/blob/1.20/common/src/main/java/net/cristellib/builtinpacks/RuntimePack.java#L21

**Comment by Cristelknight999** [comment]
Didn't know that. I got that code from somewhere online xD
