### ISSUE TITLE
crash whenever using quilt

### ISSUE THREAD

**Issue by CrystalClear51** [Cristelknight999/Cristel-Lib#7]
always crashes when using quilt, even on a completely fresh profile.

`PollyMC version: 7.2 (official)

Launched instance in offline mode

Minecraft folder is:
C:/Users/rafsu/AppData/Roaming/PollyMC/instances/1.20.1/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Java is version 17.0.8, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  org.quiltmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/rafsu/AppData/Roaming/PollyMC/instances/1.20.1/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.1/lwjgl-glfw-natives-windows-arm64-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.1/lwjgl-jemalloc-natives-windows-arm64-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.1/lwjgl-natives-windows-arm64-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.1/lwjgl-openal-natives-windows-arm64-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.1/lwjgl-opengl-natives-windows-arm64-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.1/lwjgl-stb-natives-windows-arm64-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.1/lwjgl-tinyfd-natives-windows-arm64-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/fabricmc/tiny-remapper/0.8.6/tiny-remapper-0.8.6.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/quiltmc/quilt-json5/1.0.2/quilt-json5-1.0.2.jar (missing)
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/quiltmc/quilt-config/1.0.0-beta.6/quilt-config-1.0.0-beta.6.jar (missing)
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/org/quiltmc/quilt-loader/0.19.5/quilt-loader-0.19.5.jar (missing)
  C:/Users/rafsu/AppData/Roaming/PollyMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Mods:
  [✔] cristellib-1.1.3-fabric

Params:
  --username  --version 1.20.1 --gameDir C:/Users/rafsu/AppData/Roaming/PollyMC/instances/1.20.1/.minecraft --assetsDir C:/Users/rafsu/AppData/Roaming/PollyMC/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 5036

Exception caught from launcher
java.lang.ClassNotFoundException: org.quiltmc.loader.impl.launch.knot.KnotClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:151)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
Process exited with code 2.
Clipboard copy at: 17 Oct 2023 22:04:08 +0600
`

**Comment by SettingDust** [comment]
Not relate to this mod. Checking your mod loader
